"""Public research, browser isolation, and evidence-provenance services."""

from sentinel_api.research.browser import BrowserBackend, BrowserBroker
from sentinel_api.research.evidence import (
    ClaimProvenance,
    ConflictGroup,
    EvidenceSnapshot,
    ExactSpan,
    FreshnessState,
    InMemorySnapshotStore,
    SnapshotStore,
    VerifiedObservation,
    build_verified_observation,
    find_conflicts,
    freshness_at,
    locate_exact_span,
)
from sentinel_api.research.helpers import (
    BrowserPrimitive,
    HelperManifest,
    HelperPatch,
    HelperPatchStore,
    InMemoryHelperPatchStore,
)
from sentinel_api.research.interfaces import (
    FetchTransport,
    ResearchFetch,
    ResearchSearch,
    SearchProvider,
)
from sentinel_api.research.models import (
    FetchRequest,
    RawFetchResponse,
    SearchHit,
    SearchQuery,
    SessionHandle,
    TaintedText,
    TaintLabel,
    UntrustedContent,
)
from sentinel_api.research.security import (
    InjectionSignal,
    InjectionSignalKind,
    ResearchCapability,
    ResearchGrant,
    UrlPolicy,
    scan_for_injection,
    tainted_tool_result,
)

__all__ = [
    "BrowserBackend",
    "BrowserBroker",
    "BrowserPrimitive",
    "ClaimProvenance",
    "ConflictGroup",
    "EvidenceSnapshot",
    "ExactSpan",
    "FetchRequest",
    "FetchTransport",
    "FreshnessState",
    "HelperManifest",
    "HelperPatch",
    "HelperPatchStore",
    "InMemoryHelperPatchStore",
    "InMemorySnapshotStore",
    "InjectionSignal",
    "InjectionSignalKind",
    "RawFetchResponse",
    "ResearchCapability",
    "ResearchFetch",
    "ResearchGrant",
    "ResearchSearch",
    "SearchHit",
    "SearchProvider",
    "SearchQuery",
    "SessionHandle",
    "SnapshotStore",
    "TaintLabel",
    "TaintedText",
    "UntrustedContent",
    "UrlPolicy",
    "VerifiedObservation",
    "build_verified_observation",
    "find_conflicts",
    "freshness_at",
    "locate_exact_span",
    "scan_for_injection",
    "tainted_tool_result",
]
